package ud.binmonkey.prog3_proyecto_client.gui.neo4j;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ud.binmonkey.prog3_proyecto_client.neo4j.Neo4j;
import ud.binmonkey.prog3_proyecto_client.omdb.MediaType;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;


public class LibraryForm {
    public JPanel libraryPanel;
    public JTextField searchField;
    public JComboBox typeBox;
    public JButton searchButton;
    public JPanel searchPanel;
    public JPanel titlesPanel;
    public JButton Search;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public LibraryForm() {

        titlesPanel.setLayout(new GridLayout(3, 20));

        Neo4j neo4j = new Neo4j();

        for (ArrayList<String> title : neo4j.getTitles(MediaType.ALL)) {

            addTitle("", title.get(2), title.get(1)); //TODO ad posters
        }
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        LibraryForm libraryForm = new LibraryForm();
        JPanel libraryPanel = libraryForm.libraryPanel;

        frame.setContentPane(libraryPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }

    public void addTitle(String poster, String year, String title) {

        titlesPanel.add(new TitlePanelForm(poster, year, title).titlePanel);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        libraryPanel = new JPanel();
        libraryPanel.setLayout(new BorderLayout(0, 0));
        titlesPanel = new JPanel();
        titlesPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        libraryPanel.add(titlesPanel, BorderLayout.CENTER);
        searchPanel = new JPanel();
        searchPanel.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        libraryPanel.add(searchPanel, BorderLayout.NORTH);
        searchField = new JTextField();
        searchPanel.add(searchField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        typeBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("All");
        defaultComboBoxModel1.addElement("Movie");
        defaultComboBoxModel1.addElement("Series");
        typeBox.setModel(defaultComboBoxModel1);
        searchPanel.add(typeBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchButton = new JButton();
        searchButton.setText("Search");
        searchPanel.add(searchButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return libraryPanel;
    }
}
