package ud.binmonkey.prog3_proyecto_client.gui.neo4j;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class TitlePanelForm {
    public JPanel titlePanel;
    public JLabel yearLabel;
    public JLabel titleLabel;
    public JPanel posterPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public TitlePanelForm(String poster, String year, String title) {

        ImageIcon image = new ImageIcon(poster);
        JLabel label = new JLabel("", image, JLabel.CENTER);

        posterPanel.add(label, BorderLayout.CENTER);

        titleLabel.setText(year + ". " + title);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        TitlePanelForm titlePanel = new TitlePanelForm(
                "", "1956", "Popeye for President"); //TODO add posters

        frame.setContentPane(titlePanel.titlePanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        titlePanel = new JPanel();
        titlePanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        titlePanel.add(panel1, BorderLayout.SOUTH);
        titleLabel = new JLabel();
        titleLabel.setText("Title");
        panel1.add(titleLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        posterPanel = new JPanel();
        posterPanel.setLayout(new BorderLayout(0, 0));
        titlePanel.add(posterPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return titlePanel;
    }
}
